### ISSUE TITLE
[i686] How to get ChArch/ArchLinux32 working on a 32-Bit Android tablet?

### ISSUE THREAD

**Issue by ungeskriptet** [tytydraco/ChArch-Magisk-Module#1]
I'm trying to get ChArch running on my Samsung Galaxy Tab 3, which has an Intel Atom processor, no ARM.

I alredy tried the normal ArchLinux bootstrap tarball, the transition to the ArchLinux32 repo but I am getting following error when executing ChArch:
`chroot: exec /bin/su: No such file or directory`
I checked if su is in the chroot directory, which it is.
How can I resolve this issue or get a normal ArchLinux32 tarball?

**Comment by tytydraco** [comment]
Hi! Could you send the command you used to create your rootfs instance, and the command you are using the enter it?

I've had problems with the bootstrap images before as they really aren't meant to be used as actual systems. You could go to the ChArch FAQ page in the wiki and try the Ubuntu tarball, which I've had working on my x86_64 laptop as well as my arm64 phone. 

Additionally, send me the output of `ls /data/unencrypted/charch/<name>`, where name is the rootfs name.

Which ChArch module version are you using, as well?

**Comment by ungeskriptet** [comment]
The commands I'm using are:
To create it: `# charch -n -t archlinux-bootstrap.tar.gz`
To enter it: `# charch`

I have no `/data/unencrypted` directory, even on my arm64 phone, where it works fine.

I just updated to v1.0.5 and now I'm getting a new (but similar) error on my Tab 3:
`chroot: exec /usr/bin/env: No such file or directory`

I'll try out the Ubuntu rootfs.

**Comment by tytydraco** [comment]
The /data/unencrypted folder is unique to v1.0.5, which fixes some distros. If you update to it, make sure to move your /data/local/charch to /data/unencrypted/charch (make the folder if it is missing). 

Based on the fact that it works on your arm64 phone, I'm guessing its a tarball issue, but just to confirm, let me know how the Ubuntu tarball works out.

**Comment by ungeskriptet** [comment]
Okay so I did some research about how to get the Arch Linux 32 tarball and it seems I need to pacstrap it with the Arch Linux 32 mirrorlist and then tar it. I thought the chroot would work fine except pacman itself. I currently have no access to a Linux computer, but when I have I'll try making the tarball on my own.

**Comment by tytydraco** [comment]
Ah, that makes a bit more sense. Let me know how that goes and if you get any other issues with it. I'll close the thread here 👍

**Comment by ungeskriptet** [comment]
I finally got it to work.
Here's my dirty bootstrap image: https://mega.nz/file/5g8RhI6a#DF4020XHQIBtByLRNSoZXnOql4OxxJBsTWwLiD-oUzw (MD5: `edabc09b2d1434f49e31630087df61f2`

**Comment by tytydraco** [comment]
> I finally got it to work.
> Here's my dirty bootstrap image: https://mega.nz/file/5g8RhI6a#DF4020XHQIBtByLRNSoZXnOql4OxxJBsTWwLiD-oUzw (MD5: `edabc09b2d1434f49e31630087df61f2`)

Glad you got it working!
